### PR TITLE
Use new Button properties to access keypad information.

### PR DESCRIPTION
**Pull request by colohan**

### CODE REVIEW

**Comment by colohan** [comment]
Note:  depends on corresponding pull request in pyvantage:  https://github.com/gjbadros/pyvantage/pull/6

**Review by gjbadros — COMMENTED** [review]
Does this have a dependency on another change?

**Comment by colohan** [comment]
Yes.  As mentioned above, this depends on corresponding pull request in [pyvantage: gjbadros/pyvantage#6](https://github.com/gjbadros/pyvantage/pull/6)

**Comment by gjbadros** [comment]
I finally got these reviewed (but without any real testing from me).  I did
a new 0.0.30 pyvantage release and committed and pushed a change to
hass-vantage to depend on that new version.  Can you confirm everything is
working for you as you update to the new hass-vantage head?

**Comment by colohan** [comment]
Sorry for the delay -- have had other priorities (sadly).  I'm now a homeschool teacher!

I updated everything to the latest version yesterday, and have been running since.  Seems to work great.

**Comment by gjbadros** [comment]
Great thanks for confirming!

**Pull request merged**
